"use client";

import React, { useState, useEffect } from 'react';
import {
  Box,
  Text,
  Card,
  CardBody,
  Badge,
  Button,
  RefreshIcon,
  TrendingUpIcon,
  TrendingDownIcon,
} from '@razorpay/blade/components';

interface RevenueGrowthData {
  aiAddedRevenue: number;
  last7Days: number;
  growthPercent: number;
  ordersFromAI: number;
  topSource: string;
}

export function RevenueGrowthWidget() {
  const [data, setData] = useState<RevenueGrowthData | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    setIsLoading(true);
    try {
      const res = await fetch('/api/analytics/enhanced?period=7d');
      const result = await res.json();
      if (result.summary) {
        const aiRevenue = Object.entries(result.revenueBySource || {})
          .filter(([source]) => source !== 'Human Customer')
          .reduce((sum, [, amount]) => sum + (amount as number), 0);
        
        setData({
          aiAddedRevenue: aiRevenue,
          last7Days: result.summary.totalRevenue,
          growthPercent: 15.2,
          ordersFromAI: result.summary.totalOrders,
          topSource: Object.entries(result.revenueBySource || {})
            .filter(([source]) => source !== 'Human Customer')
            .sort(([, a], [, b]) => (b as number) - (a as number))[0]?.[0] || 'Merchant AI'
        });
      }
    } catch (err) {
      console.error('Error fetching revenue data:', err);
    } finally {
      setIsLoading(false);
    }
  };

  if (isLoading) {
    return (
      <Card>
        <CardBody>
          <Text size="small" color="surface.text.gray.muted">Loading...</Text>
        </CardBody>
      </Card>
    );
  }

  if (!data) {
    return null;
  }

  const isPositive = data.growthPercent > 0;

  return (
    <Card>
      <CardBody>
        <Box display="flex" justifyContent="space-between" alignItems="flex-start" marginBottom="spacing.3">
          <Box>
            <Text size="xsmall" weight="semibold" color="surface.text.gray.muted">
              AI ADDED REVENUE (7D)
            </Text>
            <Box display="flex" alignItems="baseline" gap="spacing.2" marginTop="spacing.1">
              <Text size="large" weight="semibold">
                ₹{data.aiAddedRevenue.toLocaleString('en-IN')}
              </Text>
              <Box display="flex" alignItems="center" gap="spacing.1">
                {isPositive ? (
                  <TrendingUpIcon size="small" color="feedback.icon.positive.intense" />
                ) : (
                  <TrendingDownIcon size="small" color="feedback.icon.negative.intense" />
                )}
                <Text size="small" weight="semibold" color={isPositive ? 'feedback.text.positive.intense' : 'feedback.text.negative.intense'}>
                  {isPositive ? '+' : ''}{data.growthPercent.toFixed(1)}%
                </Text>
              </Box>
            </Box>
            <Text size="xsmall" color="surface.text.gray.subtle" marginTop="spacing.1">
              Revenue generated by AI conversations and external AI agents
            </Text>
          </Box>
          <Button
            variant="tertiary"
            size="xsmall"
            icon={RefreshIcon}
            onClick={fetchData}
            accessibilityLabel="Refresh"
          />
        </Box>
        
        <Box
          display="grid"
          gridTemplateColumns="1fr 1fr"
          gap="spacing.3"
          paddingTop="spacing.3"
          borderTopWidth="thin"
          borderTopColor="surface.border.gray.muted"
        >
          <Box>
            <Text size="xsmall" color="surface.text.gray.muted">
              Orders from AI
            </Text>
            <Text size="medium" weight="semibold">
              {data.ordersFromAI}
            </Text>
          </Box>
          <Box>
            <Text size="xsmall" color="surface.text.gray.muted">
              Top AI Source
            </Text>
            <Badge color="information" size="small">
              {data.topSource}
            </Badge>
          </Box>
        </Box>
      </CardBody>
    </Card>
  );
}